# Generated by Django 5.0 on 2024-01-31 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='username',
        ),
    ]
